apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: ssmith
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/ssmith-harbor-project/db@sha256:0a4d6a6114f32e50aa98d21dc49705778a9327f1364cb581702cb133c555f247
        ports:
        - containerPort: 5432
